import { resolve } from "node:path";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { execFileSync } from "node:child_process";

const root = resolve(import.meta.dirname, "..");
const converter = process.env.TYPLITE_BIN || "typlite";
const check = process.argv.includes("--check");
const readmeOnly = process.argv.includes("--readme-only");
const dry = process.argv.includes("--dry");
const header = "<!-- This file is generated by scripts/link-docs.mjs. Do not edit manually. -->";
const tasks = [
  ["docs/tinymist/tinymist-flow.typ", "README.md"],
  ["docs/tinymist/dev/development.typ", "docs/dev-guide.md"],
];

try {
  for (const [input, output] of readmeOnly ? tasks.slice(0, 1) : tasks) {
    const markdown = execFileSync(converter, ["--root", root, resolve(root, input), "-"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "inherit"],
    }).trim();
    const generated = `${header}\n\n${markdown}\n`;
    const path = resolve(root, output);
    if (dry) {
      process.stdout.write(generated);
    } else if (check) {
      if (readFileSync(path, "utf8") !== generated) {
        throw new Error(`${output} is out of date. Run node scripts/link-docs.mjs.`);
      }
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generated);
    }
  }
} catch (error) {
  console.error(error.code === "ENOENT"
    ? "Documentation conversion requires typlite on PATH or TYPLITE_BIN=/path/to/typlite."
    : error.message);
  process.exitCode = 1;
}
